Algoritmo "Exercício 3"
//
// Discplina   : Lógica de Programação Orientada a Objeto
// Professor   : Aldo Henrique
// Autor(a)    : Aline Lopes da Silva
// Data atual  : 03/04/2020
Var
n,d,c,s1,s2:inteiro


Inicio
n<-1
d<-1
s1<-n
s2<-n
      para c de 1 ate 50 passo 1 faca
      n<-n+2
      d<-d+1
      s1<-s1+n
      s2<-s2+d
      fimpara
      escreval("a soma é", s1, "/", s2, " que é =", s1/s2)

Fimalgoritmo